export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
// export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
// export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
// export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
// export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';
export const LOGOUT = 'LOGOUT';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';

export const TWITTER_SCRAPE_SUCCESS = 'TWITTER_SCRAPE_SUCCESS';
export const TWITTER_SCRAPE_FAIL = 'TWITTER_SCRAPE_FAIL';

export const FACEBOOK_SCRAPE_SUCCESS = 'FACEBOOK__SCRAPE_SUCCESS';
export const FACEBOOK_SCRAPE_FAIL = 'FACEBOOK__SCRAPE_FAIL';

export const TWITTER_MODEL_SUCCESS = 'TWITTER_MODEL__SUCCESS';
export const TWITTER_MODEL_FAIL = 'TWITTER_MODEL__FAIL';

export const FACEBOOK_MODEL_SUCCESS = 'FACEBOOK_MODEL_SUCCESS';
export const FACEBOOK_MODEL_FAIL = 'FACEBOOK_MODEL_FAIL';


export const TRAIN_DATA_UPLOAD_SUCCESS = 'TRAIN_DATA_UPLOAD_SUCCESS';
export const TRAIN_DATA_UPLOAD_FAIL = 'TRAIN_DATA_UPLOAD_FAIL';

export const TRAIN_FILES_UPLOAD_SUCCESS = 'TRAIN_FILES_UPLOAD_SUCCESS';
export const TRAIN_FILES_UPLOAD_FAIL = 'TRAIN_FILES_UPLOAD_FAIL';

export const CLIENT_LIST_UPLOAD_SUCCESS = 'CLIENT_LIST_UPLOAD_SUCCESS';
export const CLIENT_LIST_UPLOAD_FAIL = 'CLIENT_LIST_UPLOAD_FAIL';

export const CLIENT_DOWLOAD_SUCCESS = 'CLIENT_DOWLOAD_SUCCESS';
export const CLIENT_DOWLOAD_FAIL = 'CLIENT_DOWLOAD_FAIL';

export const TASK_UPLOADED_SUCCESS = 'TASK_UPLOADED_SUCCESS';
export const TASK_UPLOADED_FAIL = 'TASK_UPLOADED_FAIL';

export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const GET_TASK_FAIL = 'GET_TASK_FAIL';

export const TASK_UPDATED_SUCCESS = 'TASK_UPDATED_SUCCESS';
export const TASK_UPDATED_FAIL = 'TASK_UPDATED_FAIL';

export const EMAIL_UPLOADED_SUCCESS = 'EMAIL_UPLOADED_SUCCESS';
export const EMAIL_UPLOADED_FAIL = 'EMAIL_UPLOADED_FAIL';

export const USER_SUSPEND_SUCCESS = 'USER_SUSPEND_SUCCESS';
export const USER_SUSPEND_FAIL = 'USER_SUSPEND_FAIL';

export const CLIENT_EMAIL_UPLOADED_SUCCESS = 'CLIENT_EMAIL_UPLOADED_SUCCESS';
export const CLIENT_EMAIL_UPLOADED_FAIL = 'CLIENT_EMAIL_UPLOADED_FAIL';

export const FILE_DOWLOAD_SUCCESS = 'FILE_DOWLOAD_SUCCESS';
export const FILE_DOWLOAD_FAIL = 'FILE_DOWLOAD_FAIL';

export const CLIENT_TWITTER_PREDICTION_SUCCESS = 'CLIENT_TWITTER_PREDICTION_SUCCESS';
export const CLIENT_TWITTER_PREDICTION_FAIL = 'CLIENT_TWITTER_PREDICTION_FAIL';

export const CLIENT_FACEBOOK_PREDICTION_SUCCESS = 'CLIENT_FACEBOOK_PREDICTION_SUCCESS';
export const CLIENT_FACEBOOK_PREDICTION_FAIL = 'CLIENT_FACEBOOK_PREDICTION_FAIL';

export const TWITTER_SNA_SUCCESS = 'TWITTER_SNA_SUCCESS';
export const TWITTER_SNA_FAIL = 'TWITTER_SNA_FAIL';

export const TWITTER_PROFILING_SUCCESS = 'TWITTER_PROFILING_SUCCESS';
export const TWITTER_PROFILING_FAIL = 'TWITTER_PROFILING_FAIL';

export const FACEBOOK_SNA_SUCCESS = 'FACEBOOK_SNA_SUCCESS';
export const FACEBOOK_SNA_FAIL = 'FACEBOOK_SNA_FAIL';

export const FACEBOOK_PROFILING_SUCCESS = 'FACEBOOK_PROFILING_SUCCESS';
export const FACEBOOK_PROFILING_FAIL = 'FACEBOOK_PROFILING_FAIL';

export const TASK_DETAILS_SUCCESS = 'TASK_DETAILS_SUCCESS';
export const TASK_DETAILS_FAIL = 'TASK_DETAILS_FAIL';

export const DATA_UPLOAD_SUCCESS = 'DATA_UPLOAD_SUCCESS';
export const DATA_UPLOAD_FAIL = 'DATA_UPLOAD_FAIL';

export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_FAIL = 'CHANGE_PASS_FAIL';

export const TWITTER_LOGS_SUCCESS = 'TWITTER_LOGS_SUCCESS';
export const TWITTER_LOGS_FAIL = 'TWITTER_LOGS_FAIL';

export const FACEBOOK_LOGS_SUCCESS = 'FACEBOOK_LOGS_SUCCESS';
export const FACEBOOK_LOGS_FAIL = 'FACEBOOK_LOGS_FAIL';